name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: |
        vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} | tee deployment-url.txt
        echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> $GITHUB_ENV

    - name: Comment on commit
      uses: actions/github-script@v7
      with:
        script: |
          const deploymentUrl = process.env.DEPLOYMENT_URL;
          await github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: `✅ Successfully deployed to Vercel: ${deploymentUrl}`
          });

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    if: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

    - name: Build Project Artifacts
      run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: |
        vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tee deployment-url.txt
        echo "DEPLOYMENT_URL=$(cat deployment-url.txt)" >> $GITHUB_ENV

    - name: Comment on PR
      uses: actions/github-script@v7
      with:
        script: |
          const deploymentUrl = process.env.DEPLOYMENT_URL;
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `🔍 Preview deployment ready: ${deploymentUrl}`
          });